_base_: ../wan/i2v/base_train_full.yaml

dataset:
  params:
    dataset_base_path: ./data/libero_i2v_train/latent_cache
    dataset_metadata_path: null

runner:
  params:
    output_path: ./logs/train/Wan1.3B-I2V-Libero
    wandb_run_name: Wan1.3B-I2V-Libero
    task: sft:train
