task: train

runner:
  class_path: lightewm.runner.wan.wan_training.WanTrainRunner
  params:
    output_path: ./logs/train/Wan1.3B-I2V
    height: 480
    width: 832
    dataset_repeat: 100
    trainable_models: dit
    extra_inputs: input_image
    learning_rate: 1.0e-5
    batch_size: 8
    num_epochs: 999
    save_steps: 500
    remove_prefix_in_ckpt: pipe.dit.
    use_gradient_checkpointing: true
    wandb_enabled: true
    wandb_project: LightEWM
    wandb_run_name: Wan1.3B-I2V
    wandb_mode: online
    wandb_log_every: 5
    task: sft

model:
  class_path: lightewm.model.wan.pipeline.WanVideoPipeline
  params:
    device: cuda
    torch_dtype: bfloat16
    model_paths:
      - checkpoints/Wan2.1-I2V-1.3B/diffusion_pytorch_model.safetensors
      - checkpoints/Wan2.1-I2V-1.3B/models_t5_umt5-xxl-enc-bf16.pth
      - checkpoints/Wan2.1-I2V-1.3B/Wan2.1_VAE.pth
      - checkpoints/Wan2.1-I2V-1.3B/models_clip_open-clip-xlm-roberta-large-vit-huge-14.pth

dataset:
  class_path: lightewm.dataset.unified_dataset.UnifiedDataset
  params:
    dataset_base_path: ./data/your_dataset/latent_cache
    dataset_metadata_path: null

runtime:
  params:
    gradient_accumulation_steps: 1
